/** @type {import('next').NextConfig} */
const nextConfig = {
  images: { unoptimized: true },
  trailingSlash: true,
  reactStrictMode: true,
  async redirects() {
    return [
      { source: "/coaching/:path*", destination: "/", permanent: false },
      { source: "/coaching", destination: "/", permanent: false },
      { source: "/coach-guide/:path*", destination: "/resources/", permanent: false },
      { source: "/coach-guide", destination: "/resources/", permanent: false },
      { source: "/training-library/:path*", destination: "/resources/", permanent: false },
      { source: "/training-library", destination: "/resources/", permanent: false },
      { source: "/lo-development/resources/:path*", destination: "/resources/", permanent: false },
      { source: "/lo-development/video-library/:path*", destination: "/resources/", permanent: false },
      { source: "/lo-development/ai-advantage/:path*", destination: "/", permanent: false },
      { source: "/lo-development/:path*", destination: "/resources/", permanent: false },
      { source: "/lo-development", destination: "/resources/", permanent: false },
      { source: "/training-academy/:path*", destination: "/resources/", permanent: false },
      { source: "/training-academy", destination: "/resources/", permanent: false },
      { source: "/sales-training/:path*", destination: "/resources/", permanent: false },
      { source: "/sales-training", destination: "/resources/", permanent: false },
      { source: "/ai-training/:path*", destination: "/", permanent: false },
      { source: "/ai-training", destination: "/", permanent: false },
      { source: "/ai-assistants/:path*", destination: "/", permanent: false },
      { source: "/ai-assistants", destination: "/", permanent: false },
      { source: "/ai-twins/:path*", destination: "/", permanent: false },
      { source: "/ai-twins", destination: "/", permanent: false },
      { source: "/facegram/:path*", destination: "/", permanent: false },
      { source: "/facegram", destination: "/", permanent: false },
      { source: "/support-routing/:path*", destination: "/resources/", permanent: false },
      { source: "/loan-officer-support/:path*", destination: "/resources/", permanent: false },
      { source: "/loan-officer-support", destination: "/resources/", permanent: false },
      { source: "/support/:path*", destination: "/resources/", permanent: false },
      { source: "/support", destination: "/resources/", permanent: false },
      { source: "/marketing/:path*", destination: "/resources/", permanent: false },
      { source: "/marketing", destination: "/resources/", permanent: false },
      { source: "/normal-lo/:path*", destination: "/", permanent: false },
      { source: "/normal-lo", destination: "/", permanent: false },
      { source: "/lender-escalation/:path*", destination: "/resources/", permanent: false },
      { source: "/lender-escalation", destination: "/resources/", permanent: false },
      { source: "/one-plus-one-five/:path*", destination: "/", permanent: false },
      { source: "/one-plus-one-five", destination: "/", permanent: false },
      { source: "/performance-alliance/:path*", destination: "/", permanent: false },
      { source: "/inner-circle/:path*", destination: "/", permanent: false },
      { source: "/corporate-coaching/:path*", destination: "/", permanent: false },
      { source: "/team-leader-coaching/:path*", destination: "/resources/", permanent: false },
      { source: "/apex-advisor/:path*", destination: "/", permanent: false },
      { source: "/apex-advisor-pro/:path*", destination: "/", permanent: false },
      { source: "/apex-advisor-track/:path*", destination: "/", permanent: false },
      { source: "/apex-member-area/:path*", destination: "/", permanent: false },
      { source: "/apex-certifications/:path*", destination: "/", permanent: false },
      { source: "/apex-calendar/:path*", destination: "/", permanent: false },
      { source: "/apex-launch-call/:path*", destination: "/", permanent: false },
      { source: "/apex-mastermind/:path*", destination: "/", permanent: false },
      { source: "/apex-leaderboards/:path*", destination: "/", permanent: false },
      { source: "/training-path/:path*", destination: "/", permanent: false },
      { source: "/paths/:path*", destination: "/", permanent: false },
      { source: "/101-foundation/:path*", destination: "/", permanent: false },
      { source: "/201-borrower-conversion/:path*", destination: "/", permanent: false },
      { source: "/301-referral-partner-growth/:path*", destination: "/", permanent: false },
      { source: "/401-content-and-marketing/:path*", destination: "/", permanent: false },
      { source: "/401-content-marketing/:path*", destination: "/", permanent: false },
      { source: "/501-pipeline-and-sales-systems/:path*", destination: "/", permanent: false },
      { source: "/501-pipeline-sales-systems/:path*", destination: "/", permanent: false },
      { source: "/601-elite-execution/:path*", destination: "/", permanent: false },
      { source: "/content-skills/:path*", destination: "/", permanent: false },
      { source: "/audio-training/:path*", destination: "/", permanent: false },
      { source: "/new-lo-aptitude-quiz/:path*", destination: "/", permanent: false },
      { source: "/personality-quiz/:path*", destination: "/", permanent: false },
      { source: "/personality-workshop/:path*", destination: "/", permanent: false },
      { source: "/quiz-results/:path*", destination: "/", permanent: false },
      { source: "/brand-preview/:path*", destination: "/", permanent: false },
      { source: "/recommended-channels/:path*", destination: "/resources/", permanent: false },
      { source: "/compliance/:path*", destination: "/resources/", permanent: false },
      { source: "/department-routing/:path*", destination: "/resources/", permanent: false },
      { source: "/creator-network/:path*", destination: "/", permanent: false },
      { source: "/market-mentor/:path*", destination: "/resources/", permanent: false },
      { source: "/market-mentor", destination: "/resources/", permanent: false },
      { source: "/ai-coaching-assistant/:path*", destination: "/coach-command-center/", permanent: false },
      { source: "/ai-coaching-assistant", destination: "/coach-command-center/", permanent: false },
      { source: "/coach-reports/:path*", destination: "/coach-command-center/", permanent: false },
      { source: "/coach-reports", destination: "/coach-command-center/", permanent: false },
      { source: "/calendar/:path*", destination: "/resources/", permanent: false },
      { source: "/recordings/:path*", destination: "/resources/", permanent: false },
      { source: "/recordings", destination: "/resources/", permanent: false },
      { source: "/scripts/:path*", destination: "/resources/", permanent: false },
      { source: "/scripts", destination: "/resources/", permanent: false },
      { source: "/trackers/:path*", destination: "/member-area/trackers/", permanent: false },
      { source: "/trackers", destination: "/member-area/trackers/", permanent: false },
      { source: "/clip-library/:path*", destination: "/resources/", permanent: false },
      { source: "/clip-library", destination: "/resources/", permanent: false },
      { source: "/content-skills/:path*", destination: "/resources/", permanent: false },
      { source: "/content-skills", destination: "/resources/", permanent: false },
      { source: "/audio-training/:path*", destination: "/resources/", permanent: false },
      { source: "/audio-training", destination: "/resources/", permanent: false },
      { source: "/department-routing/:path*", destination: "/resources/", permanent: false },
      { source: "/department-routing", destination: "/resources/", permanent: false },
      { source: "/recommended-channels/:path*", destination: "/resources/", permanent: false },
      { source: "/recommended-channels", destination: "/resources/", permanent: false },
      { source: "/compliance/:path*", destination: "/resources/", permanent: false },
      { source: "/compliance", destination: "/resources/", permanent: false },
      { source: "/market-mentor/:path*", destination: "/resources/", permanent: false },
      { source: "/market-mentor", destination: "/resources/", permanent: false },
      { source: "/creator-network/:path*", destination: "/", permanent: false },
      { source: "/creator-network", destination: "/", permanent: false },
      { source: "/recordings/:path*", destination: "/resources/", permanent: false },
      { source: "/member-area/recordings/:path*", destination: "/resources/", permanent: false },
      { source: "/member-area/ai-assistant/:path*", destination: "/resources/", permanent: false },
      { source: "/member-area/ai-assistant", destination: "/resources/", permanent: false },
      { source: "/member-area/certifications/:path*", destination: "/member-area/", permanent: false },
      { source: "/member-area/certifications", destination: "/member-area/", permanent: false },
      { source: "/member-area/leaderboards/:path*", destination: "/member-area/", permanent: false },
      { source: "/member-area/leaderboards", destination: "/member-area/", permanent: false },
      { source: "/member-area/mastermind/:path*", destination: "/member-area/", permanent: false },
      { source: "/member-area/mastermind", destination: "/member-area/", permanent: false },
      { source: "/coach-command-center/training-plan/:path*", destination: "/coach-command-center/resources/", permanent: false },
      { source: "/coach-command-center/messages/:path*", destination: "/coach-command-center/coaching-notes/", permanent: false },
      { source: "/coach-command-center/email-center/:path*", destination: "/coach-command-center/coaching-notes/", permanent: false },
      // Pivot gap-closure: legacy standalone surfaces the redirect net missed.
      { source: "/assessments/:path*", destination: "/", permanent: false },
      { source: "/assessments", destination: "/", permanent: false },
      { source: "/tracker/:path*", destination: "/resources/", permanent: false },
      { source: "/tracker", destination: "/resources/", permanent: false },
      // AI Twin Google scopes page — dead after AI removal; keep core settings.
      { source: "/settings/google/:path*", destination: "/settings/", permanent: false },
      { source: "/settings/google", destination: "/settings/", permanent: false },
      { source: "/settings/ai-twin/:path*", destination: "/settings/", permanent: false },
      // Orphaned admin tooling for removed features (admin root stays intact).
      { source: "/admin/ai-assistants/:path*", destination: "/admin/", permanent: false },
      { source: "/admin/ai-assistants", destination: "/admin/", permanent: false },
      { source: "/admin/lender-escalations/:path*", destination: "/admin/", permanent: false },
      { source: "/admin/lender-escalations", destination: "/admin/", permanent: false },
    ];
  },
};

export default nextConfig;
